# Generated by Django 4.2.5 on 2023-10-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTable',
            fields=[
                ('customerId', models.CharField(db_index=True, max_length=250, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=250)),
                ('lastName', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('cardNumber', models.CharField(max_length=250)),
                ('birthday', models.CharField(max_length=250)),
                ('memberExpiry', models.CharField(max_length=250)),
                ('address1', models.CharField(max_length=250)),
                ('address2', models.CharField(max_length=250)),
                ('address3', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('ZIP', models.CharField(max_length=250)),
                ('rewardsPoint', models.CharField(max_length=250)),
                ('credit', models.CharField(max_length=250)),
                ('discount', models.CharField(max_length=250)),
                ('pricingLevel', models.CharField(max_length=250)),
                ('group', models.CharField(max_length=250)),
                ('notes', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
            ],
        ),
    ]
