# Generated by Django 4.2.5 on 2023-10-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertable',
            name='address3',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customertable',
            name='notes',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
