# Generated by Django 4.2.5 on 2023-10-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0004_producttable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchtable',
            name='about',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='branchtable',
            name='opening',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='branchtable',
            name='rooms',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
